### ISSUE TITLE
JSON encoding fails when starting the app

### ISSUE THREAD

**Issue by Patrick3131** [StevenLambion/SwiftUI-Todo-Example#1]
I like your implementation of containers, keeping the views itself reusable.

I tried to test the example app but I get an bad access error when starting the app in JSONStatePersistor:

```
public func encode(state: State) throws -> Data {
    try encoder.encode(state)
  }
```

I removed the PersistStateMiddleware from the Appdelegate.

When removing a TodoList from the list, @MappedState fails to unwrap a value because it is nil.

**Comment by StevenLambion** [comment]
Sorry for the late response. This was a bug introduced around Xcode 11.2. There was a fix in the swift toolchain for this, but I'm unsure if it'll be in Xcode 11.3 or a future version. I manually implemented encoding / decoding to get around this which will be in the next release of SwiftDux.
